Complete 15th homework
VladyslavAslanov/hillel-java-basic pull request #11
Opened 2023-07-16 10:14 UTC by VladyslavAslanov

2023-07-16 20:21 UTC, JIeIIIa commented on src/com/vladyslavaslanov/lesson09/FitnessTrackerUser.java
> +    private final String NAME;
SCREAMING_SNAKE_CASE використовується тільки для static final констант.

2023-07-16 20:21 UTC, JIeIIIa commented on src/com/vladyslavaslanov/lesson09/FitnessTrackerUser.java
> +    private final int CURRENT_YEAR = 2020;
Це мала б бути константа класу, а не константа обʼєкту. Якщо ти створиш 100 обʼєктів, то кожен з них буде мати поле CURRENT_YEAR == 2020 - це не доцільно

2023-07-16 20:21 UTC, JIeIIIa commented on src/com/vladyslavaslanov/lesson09/FitnessTrackerUser.java
> +    private final int AGE = CURRENT_YEAR - BIRTH_YEAR;
В даній задачі явно не вказано, що потрібно змінювати вік, але... якщо подумати логічно, то хіба вік користувача має бути константою?

2023-07-18 20:21 UTC, VladyslavAslanov commented on src/com/vladyslavaslanov/lesson09/FitnessTrackerUser.java
> +    private final int CURRENT_YEAR = 2020;
Якщо я правильно зрозумів, то рік повинен вказуватися у конструкторі. Додав визначення року у конструктор. Але все ж вказав дефолтне значення як 2020, тому що далі робиться розрахунок віку.

2023-07-20 11:03 UTC, JIeIIIa requested changes

2023-07-20 16:20 UTC, merged